CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    perfil VARCHAR(255),
    cidade VARCHAR(255),
    telefone VARCHAR(255),
    ultima_compra DATE
);

CREATE TABLE produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    categoria VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL
);

CREATE TABLE produtos_complementares (
    produto_id BIGINT NOT NULL,
    produto_complementar_id BIGINT NOT NULL,
    CONSTRAINT fk_produtos_complementares_produto
        FOREIGN KEY (produto_id) REFERENCES produto (id),
    CONSTRAINT uk_produtos_complementares
        UNIQUE (produto_id, produto_complementar_id)
);

CREATE TABLE promocao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    produto_id BIGINT,
    categoria VARCHAR(255),
    tipo_desconto VARCHAR(255) NOT NULL,
    valor_desconto DECIMAL(12, 2) NOT NULL,
    inicio DATE NOT NULL,
    fim DATE NOT NULL,
    ativa BOOLEAN NOT NULL
);

CREATE TABLE pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    data_compra DATE NOT NULL,
    CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (id)
);

CREATE TABLE itens_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    CONSTRAINT fk_item_pedido_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (id),
    CONSTRAINT fk_item_pedido_produto FOREIGN KEY (produto_id) REFERENCES produto (id)
);

CREATE TABLE notificacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    mensagem VARCHAR(2000) NOT NULL,
    canal VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    criada_em TIMESTAMP NOT NULL
);
